apiVersion: v1
kind: Secret
metadata:
    name: broadcaster-secret
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:MWWcGzxd+GubBro/WxE6YGUFJga5ldm27XJ7KJpu3PL+fuv3y7NOSZsIDJ0WNHnaNV2ARrOd8ZmHP0jScQkLPg==,iv:uzhJEvgXDeJ4pVwqwW1deEwSGDE4MwGjKfEhbq1hmCw=,tag:97eo3MjGxVBq2I5syPhgxQ==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:Jjj9zs3aoVo7pTOSUKuoiw==,iv:AhZfbAnSNSKyj077nnangzBzQuOvrpEAMzjQ2hlAJAI=,tag:0hu1GDp5uW/r4r/yGvMicQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ng3clrslk9jrqhjtp4yev3x33qwlt2tp58j5na5qm6mevej6hdxslhcqq2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d3ZrSzNmMWNMTzM0eVQr
            YjRWZW5GUjRqb2l3Wm9jUnMrRjJzMmNNMDNvCnVOYTRnVzdsT3dDT2RnUDJlU1ZD
            YU9ubFR0Uk5mdk5CTUVZenVRNFhSVEkKLS0tIDR6QWhrZGtHNkF2d0xXY1lpNHRZ
            RzhSdnk2YzNJRWJMVVgrUVpuK2IwU3cKMeAltWny9V6gTR+1QtHe8g6M13Ho5pM5
            tyxAlSPHm3MLpoA2ldcGX6qtT0/oCa8qupsZGp4gBOj2eObaE0pCSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T18:37:10Z"
    mac: ENC[AES256_GCM,data:WHFsw80jihbQNh3/3vf+SmiNyBPCAV9zBr7yFTkLDg/YAlte4xNYfpAOmH4TzN7ej/59QTogZqEXuOoR2APW3mYG95a/9y7diiu+eODKbTQjy0MLRqD3lxUKK/UNsUzuX/76bxiFXl3MUn638UIP5ia3l478zbHqP7QITtO0/Iw=,iv:0ZqBbLF+fpEqyLsc2CTru4c2NjLr0OTt/BehMSWzSPw=,tag:N+Ddy9sL84a6CxYOwyPWDw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
