apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: TODO_BROADCASTER_IMAGE
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: NATS_SERVER
              value: nats://my-nats.default.svc.cluster.local:4222
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secret
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secret
                  key: TELEGRAM_CHAT_ID
