apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dwk-project-production

resources:
  - ../../base/todo-app
  - ../../base/todo-backend
  - ../../base/todo-broadcaster
  - todo-backend/sealed-secret.yaml
