apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-project
  template:
    metadata:
      labels:
        app: todo-app-project
    spec:
      volumes:
        - name: todo-app-vol
          persistentVolumeClaim:
            claimName: ping-pong-claim
      containers:
        - name: todo-app-project
          image: vkantanen/todo-app-project:2.02
          volumeMounts:
            - name: todo-app-vol
              mountPath: /usr/src/app/static/assets/images
