apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
spec:
  metrics:
    - name: cpu-usage
      successCondition: result < 0.5
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1734-prometheus.prometheus.svc.cluster.local:9090
          query: scalar(sum(rate(container_cpu_usage_seconds_total{namespace="dwk-project-production"}[10m])))
