apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cron
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cron
              image: TODO_CRON_IMAGE
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: github-actions
          containers:
            - name: postgres-backup
              image: TODO_BACKUP_DB_IMAGE
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
          restartPolicy: OnFailure
