apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dwk-project
  name: todo-cron
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cron
              image: vkantanen/todo-cron:2.09
          restartPolicy: OnFailure
