apiVersion: v1
kind: Service
metadata:
  namespace: dwk-project
  name: todo-app-backend-svc
spec:
  type: NodePort
  selector:
    app: todo-app-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
