apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: ping-pong-vol
          persistentVolumeClaim:
            claimName: ping-pong-claim
        - name: configmap-vol
          configMap:
            name: log-output-configmap
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: log-output-reader
          image: vkantanen/log-output-reader:4.01
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: message
          volumeMounts:
            - name: ping-pong-vol
              mountPath: /usr/src/app/files
            - name: configmap-vol
              mountPath: /usr/src/app/config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: log-output-generator
          image: vkantanen/log-output-generator:1.10
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: ping-pong-vol
              mountPath: /usr/src/app/files
