apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log-output
          emptyDir: {}
      containers:
        - name: log-output-reader
          image: vkantanen/log-output-reader:1.10
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
        - name: log-output-generator
          image: vkantanen/log-output-generator:1.10
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
