---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dwk-project-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCI+fBrt5T2db/UQ8VTwJGVVxgRyv17EkaSRHy4pf85mJtWKk/8bbg6gQIrKsgk3EIr9e5yp6BsErpGlrgLjKjbP0ZS1f1VZ5YqjilD3Efbn+14Jgmu+CQ04WRYDlCEJhWCV48f6RsBgTwjzqpXO+O+d33AfgscvyieUio1MpKzS8tVNFucaltG3J2gh/jejmRoXUB5J/YcodfDY+BXAyK619/BpMiGKmZtz11UtsDfdYkoK+vSN+JvzbVl0Xjjb9S0Oa/SyW0uqg7fD3MjcsoEiDlYLG6gBCVhqDBPFMgrYRTTthh0je2j+euluXho0NlstnbxA9WSBjLAKfWZ+HI3c243A6CQKb0dpzuiCMTr1W1FpurmfMErHVaofPExG+xcsMYpk70cMzetRl14vb22jBmX55hBLky0D6ii6l38V490+ME56NKAeGwjJcF7TrxR6FTgxdEcxKc9MQ6sC52v6KJEnoMhEfINFigyxkyzfBJH6Mn0aevUyteWl7SGEu11UqlEyiyVOdKvmO++nGwvIpWlF4OvdiEYbkGHjt/xGbFJ0Gx0eaXv9zqh7D4B924gzrPJnaYgJ8RBk5kHHtv/SQaAW53r4jWfwADhB1EyYM5fqnGieUJsENcNaWbLmW4NCCYKmj9i2fMDsaetEGqfHjl9EGJ/kBh5mQgYHE6m2KGptXZQz5pY2+PZ3hCXaw7BnCmE3991XxtiZ9JRuqTlBYjp/I5m8Vth
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dwk-project-staging
