apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: ping-pong-vol
          persistentVolumeClaim:
            claimName: ping-pong-claim
      containers:
        - name: ping-pong
          image: vkantanen/ping-pong:1.11
          volumeMounts:
            - name: ping-pong-vol
              mountPath: /usr/src/app/files
