apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: dwk-exercises
  name: ping-pong
spec:
  template:
    spec:
      containers:
        - image: PING_PONG_IMAGE
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
