---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dwk-exercises
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA5/5f/shFdVrclGQdvzcBhuV3qgfejIskE050EwS7qP95yFq1s4Qf6wEAzbHWM004XzXMuL6TazkDS4ZCx4cXM9rkZK16z3gwLt/fxNg6BrW0++m5vA0yLEhdFoY/XReJARi0kJCNP/DOjH5NuZXFxNKl9etsHi93kIuVUlan8kRtiegWJvzEmGil5FAhJSJDBFki8sFxDVuwKnpTZdbYPyUKPxBPbHsZBXToSms79kNSF3zi0npGmOwYQXh5UPt6Sjne4Y+KVV1XX0cPuuOuKP+YXYdYtZw7VF3uFg45lYS+1H6jdnJe5NAMuwQbwU4vfd2DCtT04oJZqNqpQEJTM7ajJlqns9sPw3ERr+ON3BRPE3S2czCa4qWAnfWeyPSkql+CIi01olmUo/xO31H48KaGcTH4iGCtYxmVPOk1BqBVuNpNKU1CzN5ZEMJ3NIg1aV6QGwK05Cd5jcabm9FvHKn6NVxycQZ4Dw35RKYAWdvJAGiv8ojfX9CMDOm5Xm2LJCjYMwLqgFdPoT5GgWyVrH+SX6zemCipK86Lgd4XeNqfmQXix6Tq/V7tSiEi+UwzPlnA8at6/HLl90S4nWvjvH2nYHEI0LpjwhVattsi3MMl2S3kuK55RTuoGfs2EJWjcKjqcHuHueLceh2Wi9c0xbsGYRZBGa1kE6Hz1LiKPkrF9+m6EDBqM8eKZ1XTGLnlWxC6GXeDwz3h9qoDFBImBSWXti64owTdX
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dwk-exercises
