apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/kservice.yaml
- manifests/postgres.yaml
- manifests/sealed-secret.yaml

images:
- name: PING_PONG_IMAGE
  newName: vkantanen/ping-pong
  newTag: 41d0668374d1bdd0e3ac5568b2b7f5aafc225473
