---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dwk-project-production
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAmPeIq2VDvzVU4XL8G2i8pj2whgaAhPWIaG7OnbCMKmTc6KvEG/wilS+UNx1RV+8tfv4yRudzQhUZBUgi8nrdo2EN4Cm5TumEqTwFO0jIPizEzM3vrLwGu23F2rjxDue99VIFU0KUpss5gCHFIM4c35xZ9SE/rH3UYIRC6K0fB1xZQxnxgFX5AQxR3Njfw0LO531ypc2Y/7h+3V6WiLjxBLGvTi2hWGVqJHDnD7eS9wNHUaVcK5dSygomsiM3DbJiZcCwFMce9A5810+fLHNTfAeJ7T4AH19sJPW4X2ttwJhJUE3cBF/T5XnYDszXcsvjoKfXZzqJ+bNyPeIRlH6l3QmqegzzxcvumOcq2PAhIxVJ6djzPoOGyDQKrjZM2f6520KTlXaMESgpBp8+s+1LuvBTrYhpbCoOTkgawF0yHBieL/IhBzcu2MlzoyLsDrO08xmHAS2FLTuaHge2wnJmQITKEY2TV+F7ERGU2bfeHS5IMxvMvBkDVsv9PzkEY+Pl2aA6gaBiRNG6GG7qPerzNTNIXBVOfyBOGOvWvpNQGcav7zTl9Na+BKZSincortL89KoYzzbBFlSS7jSVpwWerxfRc4sJccNZhq9UuHmDJQ9b4VnK7DAlyK8A1ncDbkAVHJJAPRlXtXQwpecCvdv2pIv6g41D0wgFdpNqxxEcUqU5pLwhI+V/cFv5jn/VfaPQEXnTIwnZUm11NmvRb3FhaG5yB892qPzt+
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dwk-project-production
