---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: broadcaster-secret
  namespace: dwk-project-staging
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgC8qS6XdOkOcEmkfHznr9Y/6MWUUI09v9nLVYeNb9uNw8Lb5zBuhZ/OKgkBwGw3JwVAKYw7Zcw8qIIHDxmgBn7L7JQxt8ZqvB6jv82ZHa689PE7ZnVdI6RuP809QAnSHEIJU/gr9m6hkWWq4Oh9VdXeToCZnLTkfDBAquf2AaxEoXleVoWAkD292YfAcSxrb248XzVOKegX28pzcRCWYRmi7MXcQN26XPTPZvnJD8ZW4FDsRjSfhYYzjjMc8u66+0bluJEjK5fnFDDuU6soYjpE65eY+PfJhIoN35hlA4McB/cmg7w5XpNTiTGwwkab6n594flkvw5bKsVOnmEGTiYCTALt8IeXSgiFGrCWICuV9n+P2+71j/HKRP9lY+DhgiC2/ocdLzz0GUwabxi87IHK1128+NDttPOtvpluyduXD4eEGSSQ1nCQSkWqQasRnxvkayHt4W9PwgI3gLKpPBUWjs64MhQ0vld8nahETIku+m3gbbp7pCAVvrMV5KwZgtSx7PYUNgBiGjVfcNDTX4aTVV2DlBp3CldldCGzlU0Rp3mnENoNyUzT05wZ30WLF3geWNYCCciKdg2m75WUoSlfEtZidIvZMdllwvltGxFWrMDNpnec7F68XmiVKWpBZ41m15EkxMWXAJkamdO4zn1Kql7+4FRMWuOE5wfKPDuNpsOpvHLDqfb05EW3ReCw9c2Er0q/aLJwrZJZbGFEs3jlFcuW21bgvWZaef4HGqVVcpD+OTOmFE46lLv2ctR0
    TELEGRAM_CHAT_ID: AgBuJ1HmscqTVv1u3ZG7mEFJYANsEOK9Rla/tbr2xCvoVFclGncovwAoXe8cmslesitkZp8ImcEGlX1WFtakjOcx4zVBMD8K19THpSWGOs5ivF7KacI+fBcA2ERlhcFXKiU0KMs1W292NCADy6cPD11zTGX9lBMSkbN6zktBR1AVqlYVIyBRtsr903FpmIYKtKF3n0p+IHVILSUWGIkGvvGVg3pMUAV+xo+nJfmfAF9YSylY0TisJUew1mskcpmfkpibiaQRF8Ka0BPtMmhU4TcZW3ZGppsvhgovYw6JmGf32t4BbWfmP8wn19mRRDxxDng7X9vShFVvhRylDMocOPRfEJlWYt3tt2s7ESq8rH0rv0t+cpe0CgODBxthMJEiAj/Ol5N3EJx1NPKv71qHSv8EfetzNBI/6OxfDOlIgl3A4I1Mn0xKg74RC1vm6Rs+CaqGHGEfPhHBKfAVA4dLDqd2jCk/IPs8fZwO0BzGgRz949zmVrE3JroZLQKoJ21MTuc7LHdx1IIo8z5KaSJKil9URsnxGxIajk4YScTIj/SHjnZN+OkK44ncvxWjwntcyLKnUNIQ7BszJPXsJsZKGspyWksCbUeWR7NOezxSeG1UHAXqB7kO8jN4Ji9A5Zca/VbFYuMPXIoC5TvofRWhNKdySaPnAQfCz/pCph3e0K4819yWifaOky6N0VOwIJW7V4s5wququ5vjOj1U+w==
  template:
    metadata:
      creationTimestamp: null
      name: broadcaster-secret
      namespace: dwk-project-staging
