---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: broadcaster-secret
  namespace: dwk-project-production
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgB+ountvpmtQhHf8xLLMfrMOQjmQJ7PeXFdLgxOxFi4wXf9ttOh4knpa+5ExwpU2nijSzOqygJerK5x9ebrFb7UlzF++EHJ5NeYiI+OFj4gp6/xWpKhtWAjEB2QhcB1hQ10Hp0u8KhYLTdOADEWeB0FW/uuc4ZORcvd671uJ3uSEPnHfAWPkVkz06taeOnaRvTGJ2PAmkZeGHGuuQolkmRT+uQ7F6SdfEOiT9LnjZuamd2kG9uB0ds8C+q44g202byKd08SSqsVDU7mn2mvqzZ13VmikrsSxzwHu+IfUL1Ox6FK8MFePM2VGJ2nxuk/wzNMxBy9eZukekEAlpMq9u5phDVrDN3aUe6vUbnxAdSwlJ9ySRbqW2WGH1y+s8MEhbJ1OFxqZkFLhAwrhGNVtC7Q4uPVkAW3iAoJjO+QQQG+JyN2YU9Q21H4O5O+wU7CS4k/X53CUZXl+sd9btrpwRJQS2VtK9U6QK8iT8Vz/QPmwvfDolq0UAZZzbfSvYRJbgvV2vxH/xoFUri4xH/KYkZ+NlQpAmtJwA5sVIlfAyS4prlVFPIFI3UaHrBSHj+RDpTjtPE/VJ3y2gSDtFtg8lxXCGBDJ7vZM53ISRuQrCYul9UtzmD/gzLc2Ar4rLdoSlAmljf+We07bFLo/UZQ6AoQ+8FHcKTvAwnaUoy3q4kNoFm5OIynZAIQQiMPfUtc42dEgds1tc1ycRfgaSwS7uBFTubxRggX/ZGYwAOhUzGB8x5j7O3zR70Sall428Gd
    TELEGRAM_CHAT_ID: AgBiTgLAm1XRhnTfRLMvqoMle3s0pE7+w7QRCL7nsbcJTfSR5ZqY4Flz0nXUFFYv6do8Jaf1w4NsVTdYgowsTzbDYlu/bu8ZBcj2kPmbNZzZSqdEpRLcWwp7+u26CT+2hj3BAzZI5Xj9iXw4L8RtXlUmlB7gli9vhRM3oIFbU+rlR8CY+GziNGzxJGdxwlDd6yGXyliu+6smIRbOonKYYxe1XLwIixtfOC/KYO0tl+V9A1JxT99XrWXTU/mFMmuYB05qxn2UNkNs4HOqWPb0kBcH3YTuVhVGl8Gr8cb78uzNbT57FYTWVW+5tKfdCGMY1VkJoPEz2qk0du7QkQP+6vHasKpYFYZyC/DPkj9rY3tyjvJmKg5Xn8MZPEMsYIfxHhp5o+3T8GeHDjwPk0+AqTk6Ni68EyxsiIek5Up5JaqbX3Q2SCECHEVQncV7OUyBiMG+k8+6h9bpWEUikLfBwY5+hPuSMXVB9gOPcO4Y6NBtdmBGQvf2iRCXM68MG1qyA8BcLY+r/2Mb2Kyy0Cc3wJbWJj6aMcGnA/1BoL1MitXw1y+513EZWadMURs6YGc4kjav2NPSEsHCpdvc3dhxDyPaGKS2B/kMiD2dWzAJm9yoyw0KqS+xTmgxiG0bBRhxND8TY/HHeUDqh6Nny3FnNZ3fMzhYYtbobYzgfqhKAk7tsBA5Wd4BqzgqrJSH5VKINyteMrBSb605ZSG3pw==
  template:
    metadata:
      creationTimestamp: null
      name: broadcaster-secret
      namespace: dwk-project-production
