name: Clean up environment

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  clean-up-environment:
    name: Clean up environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Set namespace
        run: |
          if [[ "${BRANCH}" != "main" ]]; then
            echo "NAMESPACE=${BRANCH}" >> $GITHUB_ENV
          else
            echo "Branch 'main' cannot be deleted." && exit 1
          fi

      - name: Delete environment
        run: |
          if kubectl get namespace ${NAMESPACE}; then
            kubectl delete namespace ${NAMESPACE}
          else
            echo "Namespace ${NAMESPACE} does not exist, nothing to delete."
          fi
