name: Build and publish project to production

on:
  push:
    tags:
      - '*'

jobs:
  build-publish:
    name: Build, push and publish to production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to the main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish application
        working-directory: todo-app-project
        run: |-
          docker build --tag vkantanen/todo-app-backend:${GITHUB_SHA} todo-backend/src
          docker build --tag vkantanen/todo-app-project:${GITHUB_SHA} todo-app/src
          docker build --tag vkantanen/todo-app-backup-db:${GITHUB_SHA} backup-database
          docker build --build-arg NODE_ENV=production --tag vkantanen/todo-broadcaster:${GITHUB_SHA} todo-broadcaster/src
          docker build --tag vkantanen/todo-cron:${GITHUB_SHA} todo-cron
          docker push vkantanen/todo-app-backend:${GITHUB_SHA}
          docker push vkantanen/todo-app-project:${GITHUB_SHA}
          docker push vkantanen/todo-app-backup-db:${GITHUB_SHA}
          docker push vkantanen/todo-broadcaster:${GITHUB_SHA}
          docker push vkantanen/todo-cron:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update images in kustomization.yaml
        working-directory: todo-app-project/overlays/prod
        run: |-
          kustomize edit set image TODO_APP_IMAGE=vkantanen/todo-app-project:${GITHUB_SHA}
          kustomize edit set image TODO_BACKEND_IMAGE=vkantanen/todo-app-backend:${GITHUB_SHA}
          kustomize edit set image TODO_BACKUP_DB_IMAGE=vkantanen/todo-app-backup-db:${GITHUB_SHA}
          kustomize edit set image TODO_CRON_IMAGE=vkantanen/todo-cron:${GITHUB_SHA}
          kustomize edit set image TODO_BROADCASTER_IMAGE=vkantanen/todo-broadcaster:${GITHUB_SHA}

      - name: Commit changes to kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'todo-app-project/overlays/prod/kustomization.yaml'
          message: New version ${{ env.TAG_NAME }} released to production
